# Generated by Django 5.1.7 on 2025-04-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upfrica_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helparticle',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='helparticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='helparticle',
            name='content',
        ),
        migrations.AddField(
            model_name='helparticle',
            name='body',
            field=models.TextField(default='Coming soon...', help_text='Full article content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helparticle',
            name='images',
            field=models.JSONField(blank=True, help_text='List of image URLs (stored as JSON)', null=True),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='lastmod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='note',
            field=models.TextField(blank=True, help_text='Optional footnotes or extra info'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='summary',
            field=models.TextField(blank=True, help_text='Short summary or meta description'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=250),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='tips',
            field=models.TextField(blank=True, help_text='Optional tips section'),
        ),
    ]
