# Generated by Django 5.1.7 on 2025-04-01 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upfrica_backend', '0002_rename_created_at_helparticle_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helparticle',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this article belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='upfrica_backend.helpcategory'),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
